/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pdale' at '8/7/15 5:34 PM' with Gradle 2.5
 *
 * @author pdale, @date 8/7/15 5:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
